#!/usr/bin/env python3
"""
ai-setup: Project scaffolding script.

Creates the full folder structure, writes .clinerules / CLAUDE.md,
initialises a uv project, and adds a .gitignore.

No packages are installed. Dependency selection happens in ai-agent-domain-expert ideation
(Stage 1.5); installations run in ai-agent-developer infra (Stage 5) via `uv sync`.
"""

import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# .clinerules template (Cline / Cursor / Antigravity)
# ---------------------------------------------------------------------------
CLINERULES_TEMPLATE = """\
# AI Lifecycle — Skill Reference
# Auto-generated by ai-setup. Edit paths if your submodule location differs.
#
# HOW TO USE (Cline / Cursor):
#   There are no slash commands. To invoke an agent, tell the AI:
#   "Follow the workflow in: <path below>"
#   or paste the path into your system prompt / context.

## Lifecycle Agents (invoke in order)

- Stage 1   — Domain research:        .claude/skills/ai-lifecycle/ai-agent-domain-expert/SKILL.md  (capability: domain-research)
- Stage 1.5 — Ideation / PRD:         .claude/skills/ai-lifecycle/ai-agent-domain-expert/SKILL.md  (capability: ideation)
- Stage 2   — EDA:                    .claude/skills/ai-lifecycle/ai-agent-data-engineer/SKILL.md   (capability: eda)
- Stage 3   — Architecture:           .claude/skills/ai-lifecycle/ai-agent-researcher/SKILL.md      (capability: architecture)
- Stage 4   — Detailed Design:        .claude/skills/ai-lifecycle/ai-agent-researcher/SKILL.md      (capability: detailed-design)
- Stage 4.5 — TECHSPEC:               .claude/skills/ai-lifecycle/ai-agent-developer/SKILL.md       (capability: techspec)
- Stage 5   — Infrastructure:         .claude/skills/ai-lifecycle/ai-agent-developer/SKILL.md       (capability: infra)
- Stage 6   — Experiment:             .claude/skills/ai-lifecycle/ai-agent-engineer/SKILL.md        (capability: experiment)
- Stage 7   — Analysis:               .claude/skills/ai-lifecycle/ai-agent-researcher/SKILL.md      (capability: analysis)
- Stage 7.5 — HPO (conditional):      .claude/skills/ai-lifecycle/ai-agent-engineer/SKILL.md        (capability: hparam)
- Stage 8   — Revision:               .claude/skills/ai-lifecycle/ai-agent-domain-expert/SKILL.md   (capability: revision-audit)

## Universal Tools (invoke anytime)

- Advise (surface past findings):     .claude/skills/ai-lifecycle/ai-agent-domain-expert/SKILL.md   (capability: advise)
- Retrospective (capture learnings):  .claude/skills/ai-lifecycle/ai-agent-researcher/SKILL.md      (capability: retrospective)
- Inference pipeline:                 .claude/skills/ai-lifecycle/ai-agent-developer/SKILL.md        (capability: inference-pipeline)

## Experiment Tracking

Chosen tool: {tracking_tool}
Configure in ai-agent-developer infra (Stage 5).

## LLM Engine

The model is set in your IDE settings — not here.
For scripts calling an LLM programmatically: configs/llm_config.yaml + scripts/llm_client.py

## Key Principles

- No packages installed until ai-agent-developer infra (Stage 5) runs `uv sync`.
- Package requirements are written to pyproject.toml in ai-agent-domain-expert ideation (Stage 1.5).
- TECHSPECs are contracts — never modify after training starts.
"""

# ---------------------------------------------------------------------------
# CLAUDE.md template (Claude Code)
# ---------------------------------------------------------------------------
CLAUDE_MD_TEMPLATE = """\
# AI Lifecycle — Project Rules
# Auto-generated by ai-setup.

## Available Agents

| Slash Command | Stages | Role |
|---------------|--------|------|
| /ai-agent-domain-expert | 1, 1.5, 8, anytime | Domain Expert — domain research, problem framing, PRD, advise, revision audit |
| /ai-agent-data-engineer | 2 | Data Engineer — EDA, baseline, data quality |
| /ai-agent-researcher | 3, 4, 7, anytime | AI Researcher — architecture, detailed design, analysis, retrospective |
| /ai-agent-developer | 4.5, 5, anytime | AI Developer — TECHSPEC, infrastructure, inference pipeline |
| /ai-agent-engineer | 6, 7.5 | AI Engineer — experiments, HPO |

After invoking an agent, tell it which capability to activate (e.g. "run domain-research", "run architecture").

## Experiment Tracking

Chosen tool: {tracking_tool}
Configure in ai-agent-developer infra (Stage 5).

## LLM Engine

The model executing these agents is the one selected in your Claude Code model picker.
No project-level override needed.

For scripts that call an LLM programmatically:
  Config: configs/llm_config.yaml  (provider / model / api_key_env / base_url)
  Usage:  from scripts.llm_client import LLMClient

## Package Management

This project uses **uv**. Do NOT use pip or python -m venv.

- Add packages: `uv add <package>`
- Sync environment: `uv sync`
- Run scripts: `uv run python scripts/...`

Packages are added to pyproject.toml in ai-agent-domain-expert ideation (Stage 1.5).
The first `uv sync` runs in ai-agent-developer infra (Stage 5) as part of the smoke test.
"""

# ---------------------------------------------------------------------------
# .gitignore
# ---------------------------------------------------------------------------
GITIGNORE = """\
# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
.uv/

# uv
uv.lock

# Jupyter
.ipynb_checkpoints/
*.ipynb

# AI/ML artifacts
checkpoints/
*.ckpt
*.pt
*.pth
*.onnx
*.tflite
*.pkl
*.joblib

# Experiment tracking
mlruns/
wandb/
logs/
*.log

# Data (keep structure, ignore content)
data/raw/*
data/processed/*
data/splits/*
!data/raw/.gitkeep
!data/processed/.gitkeep
!data/splits/.gitkeep

# Secrets
.env
*.env
secrets.json

# OS
.DS_Store
Thumbs.db
"""

# ---------------------------------------------------------------------------
# pyproject.toml skeleton (uv-compatible, no dependencies)
# ---------------------------------------------------------------------------
PYPROJECT_TEMPLATE = """\
[project]
name = "{project_name}"
version = "0.1.0"
description = "Generated by ai-setup. Add description after ai-agent-domain-expert ideation."
requires-python = ">={python_version}"
dependencies = []
# Dependencies are added in ai-agent-domain-expert ideation (Stage 1.5) and installed
# in ai-agent-developer infra (Stage 5) via: uv sync

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov>=5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
"""


def create_dirs(root: Path, project_name: str) -> None:
    dirs = [
        "docs/prd",
        "docs/eda",
        "docs/architecture",
        "docs/design",
        "docs/techspecs",
        "docs/implementation",
        "docs/experiments",
        "docs/revisions",
        "docs/knowledge",
        "data/raw",
        "data/processed",
        "data/splits",
        f"src/{project_name}",
        "tests",
        "scripts",
        "logs",
        "notebooks",
        "configs",
    ]
    for d in dirs:
        (root / d).mkdir(parents=True, exist_ok=True)

    # Placeholder files so git tracks empty dirs
    for d in ["data/raw", "data/processed", "data/splits", "logs"]:
        keep = root / d / ".gitkeep"
        if not keep.exists():
            keep.touch()

    # Minimal __init__.py files
    for init_dir in [f"src/{project_name}", "tests"]:
        init_file = root / init_dir / "__init__.py"
        if not init_file.exists():
            init_file.write_text("", encoding='utf-8')


def write_clinerules(root: Path, ide: str, tracking_tool: str) -> None:
    content = CLINERULES_TEMPLATE.format(tracking_tool=tracking_tool)
    if ide == "claude-code":
        out = root / ".claude" / "CLAUDE.md"
        out.parent.mkdir(exist_ok=True)
        out.write_text(CLAUDE_MD_TEMPLATE.format(tracking_tool=tracking_tool), encoding='utf-8')
        print(f"  Wrote: .claude/CLAUDE.md")
    else:
        out = root / ".clinerules"
        out.write_text(content, encoding='utf-8')
        print(f"  Wrote: .clinerules")


def write_gitignore(root: Path) -> None:
    gi = root / ".gitignore"
    if not gi.exists():
        gi.write_text(GITIGNORE, encoding='utf-8')
        print(f"  Wrote: .gitignore")
    else:
        print(f"  Skipped: .gitignore (already exists)")


def write_pyproject(root: Path, project_name: str, python_version: str) -> None:
    pf = root / "pyproject.toml"
    if not pf.exists():
        pf.write_text(PYPROJECT_TEMPLATE.format(
            project_name=project_name,
            python_version=python_version,
        ), encoding='utf-8')
        print(f"  Wrote: pyproject.toml (no dependencies — added in Stage 1.5)")
    else:
        print(f"  Skipped: pyproject.toml (already exists)")


def write_python_version(root: Path, python_version: str) -> None:
    pv = root / ".python-version"
    if not pv.exists():
        pv.write_text(python_version + "\n", encoding='utf-8')
        print(f"  Wrote: .python-version ({python_version})")


def run_uv_init(root: Path, project_name: str) -> None:
    """Run `uv init` to initialise the project, then clean up uv's boilerplate."""
    pf = root / "pyproject.toml"
    existed_before = pf.exists()

    result = subprocess.run(
        ["uv", "init", "--name", project_name, "--no-readme", "--no-workspace"],
        cwd=root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        if not existed_before:
            print(f"  Warning: `uv init` failed ({result.stderr.strip()}). Will write pyproject.toml manually.")
        else:
            print(f"  Skipped: uv init (pyproject.toml already exists)")
        return

    print(f"  Ran: uv init")

    # uv init creates main.py — remove it, we use src layout
    main_py = root / "main.py"
    if main_py.exists():
        main_py.unlink()
        print(f"  Removed: main.py (using src/ layout instead)")

    # Overwrite uv's minimal pyproject.toml with our richer template
    if not existed_before:
        pf.unlink(missing_ok=True)


def write_llm_config(root: Path, skill_dir: Path) -> None:
    """
    Copy llm_config.yaml.template to configs/llm_config.yaml in the project.

    This config is ONLY for scripts that call an LLM programmatically via
    llm_client.py. The model running the agent prompts is set inside
    the IDE (Cline / Antigravity / Claude Code) — not here.
    """
    dest = root / "configs" / "llm_config.yaml"
    if dest.exists():
        print(f"  Skipped: configs/llm_config.yaml (already exists)")
        return

    template = skill_dir.parent / "configs" / "llm_config.yaml.template"
    if template.exists():
        shutil.copy2(template, dest)
        print(f"  Wrote: configs/llm_config.yaml (edit to configure programmatic LLM calls)")
    else:
        dest.write_text(
            "# AI Lifecycle LLM config — for scripts/llm_client.py only.\n"
            "# The agent model is set in your IDE settings.\n"
            "provider: anthropic\n"
            "model: claude-sonnet-4-6\n"
            "base_url: ~\n"
            "api_key_env: ANTHROPIC_API_KEY\n"
            "max_tokens: 8192\n"
            "temperature: 0.0\n",
            encoding='utf-8',
        )
        print(f"  Wrote: configs/llm_config.yaml (minimal fallback — template not found)")


def register_in_bmad_help(root: Path, skill_dir: Path) -> None:
    """
    Register all ai-lifecycle skills in _bmad/_config/bmad-help.csv.
    """
    csv_path = root / "_bmad" / "_config" / "bmad-help.csv"
    if not csv_path.exists():
        print(f"  Skipped: {csv_path} not found (not a BMAD project root?)")
        return

    our_csv = skill_dir.parent.parent / "ai-lifecycle.csv"
    if not our_csv.exists():
        print(f"  Skipped: ai-lifecycle.csv not found in module root")
        return

    existing = csv_path.read_text(encoding="utf-8")
    our_rows = our_csv.read_text(encoding="utf-8").strip()

    # Remove any existing ai rows, then append current ones
    kept = [line for line in existing.splitlines() if not line.startswith("ai,")]
    updated = "\n".join(kept).rstrip() + "\n" + our_rows + "\n"
    csv_path.write_text(updated, encoding="utf-8")
    print(f"  Updated: _bmad/_config/bmad-help.csv (ai-lifecycle rows replaced)")


def copy_claude_skills(root: Path, skill_dir: Path) -> None:
    """
    Copy all ai-lifecycle SKILL.md + bmad-manifest.json files into .claude/skills/
    so that Claude Code can discover them as slash commands.
    """
    module_root = skill_dir.parent.parent  # scripts/ -> ai-setup/ -> ai-lifecycle/
    dest_root = root / ".claude" / "skills"
    dest_root.mkdir(parents=True, exist_ok=True)

    copied = []
    for agent_dir in module_root.glob("ai-agent-*/"):
        skill_md = agent_dir / "SKILL.md"
        manifest = agent_dir / "bmad-manifest.json"
        if not skill_md.exists():
            continue
        dest_skill = dest_root / agent_dir.name
        dest_skill.mkdir(exist_ok=True)
        shutil.copy2(skill_md, dest_skill / "SKILL.md")
        if manifest.exists():
            shutil.copy2(manifest, dest_skill / "bmad-manifest.json")
        copied.append(agent_dir.name)

    if copied:
        print(f"  Copied {len(copied)} agents → .claude/skills/ (slash commands now available)")
    else:
        print(f"  Warning: no agent skill files found to copy into .claude/skills/")


def copy_scripts(root: Path, skill_dir: Path) -> None:
    """Copy ai-lifecycle utility scripts (including llm_client.py) into project scripts/."""
    scripts_dir = root / "scripts"
    module_root = skill_dir.parent.parent

    copied = []

    # Copy llm_client.py from our own scripts dir
    llm_client_src = skill_dir / "llm_client.py"
    if llm_client_src.exists():
        dest = scripts_dir / "llm_client.py"
        if not dest.exists():
            shutil.copy2(llm_client_src, dest)
            copied.append("llm_client.py")

    # Copy all other utility scripts from agent script directories
    for agent_scripts in module_root.glob("ai-agent-*/scripts/*.py"):
        if agent_scripts.name.startswith("test_") or agent_scripts.name == "llm_client.py":
            continue
        dest = scripts_dir / agent_scripts.name
        if not dest.exists():
            shutil.copy2(agent_scripts, dest)
            copied.append(agent_scripts.name)

    if copied:
        print(f"  Copied {len(copied)} utility scripts → scripts/")
    else:
        print(f"  No utility scripts found to copy (run from skill directory)")


def _ask(prompt: str, default: str, choices: list[str] | None = None) -> str:
    """Prompt the user for input, showing the default and optional choices."""
    if choices:
        options = "/".join(
            f"[{c}]" if c == default else c for c in choices
        )
        display = f"{prompt} ({options}): "
    else:
        display = f"{prompt} [{default}]: "
    try:
        answer = input(display).strip()
    except (EOFError, KeyboardInterrupt):
        print()
        sys.exit(0)
    return answer if answer else default


def main() -> None:
    root = Path.cwd()
    project_name = root.name.replace("-", "_").replace(" ", "_")

    print(f"\nai-setup: Scaffolding '{project_name}' in {root}\n")

    ide = _ask(
        "IDE",
        "cline",
        choices=["claude-code", "cline", "cursor", "antigravity"],
    )
    tracking_tool = _ask(
        "Experiment tracking tool (can be changed in Architecture stage)",
        "undecided",
        choices=["wandb", "mlflow", "clearml", "undecided"],
    )
    python_version = _ask("Python version", "3.11")
    copy_scripts_flag = _ask("Copy ai-lifecycle utility scripts?", "yes", choices=["yes", "no"])

    print()

    print("Creating directory structure...")
    create_dirs(root, project_name)

    print("Writing config files...")
    write_clinerules(root, ide, tracking_tool)
    write_gitignore(root)
    write_python_version(root, python_version)

    print("Initialising uv project...")
    run_uv_init(root, project_name)
    write_pyproject(root, project_name, python_version)

    print("Writing LLM config...")
    script_dir = Path(__file__).parent
    write_llm_config(root, script_dir)

    print("Registering skills in bmad-help.csv...")
    register_in_bmad_help(root, script_dir)

    if ide == "claude-code":
        print("Copying agents to .claude/skills/ (enables slash commands)...")
        copy_claude_skills(root, script_dir)

    if copy_scripts_flag != "no":
        print("Copying ai-lifecycle utility scripts...")
        copy_scripts(root, script_dir)

    if ide in ("cline", "cursor"):
        stage1_instruction = (
            '  Open your IDE and tell the AI:\n'
            '  "Follow the workflow in: .claude/skills/ai-lifecycle/ai-agent-domain-expert/SKILL.md"\n'
            '  Tell it to activate the domain-research capability.\n'
            '  (All agent paths are listed in .clinerules for quick reference)'
        )
    else:
        stage1_instruction = "  Use slash command: /ai-agent-domain-expert  (then: activate domain-research)"

    print(f"""
Project scaffolded at: {root}

Next steps:
  1. Set up environment: uv venv && source .venv/bin/activate  (or use uv run)
  2. Start Stage 1 — Domain Expert researches the problem space:
{stage1_instruction}
     The agent determines required packages and writes them to pyproject.toml.
  3. Stage 5 (ai-agent-developer infra) runs: uv sync  <- FIRST package installation.

Do NOT run `uv sync` or `uv add` before Stage 5.
""")


if __name__ == "__main__":
    main()
