#!/usr/bin/env python3
"""
ai-setup: Project scaffolding script.

Creates the full folder structure, writes .clinerules / CLAUDE.md,
initialises a uv project, and adds a .gitignore.

No packages are installed. Dependency selection happens in ai-agent-domain-expert ideation
(Stage 1.5); installations run in ai-agent-mlops-engineer infra (Stage 5) via `uv sync`.
"""

import argparse
import os
import shutil
import subprocess
import sys
import textwrap
from pathlib import Path


# ---------------------------------------------------------------------------
# .clinerules template (Cline / Cursor / Antigravity)
# ---------------------------------------------------------------------------
CLINERULES_TEMPLATE = """\
# AI Lifecycle — Skill Reference
# Auto-generated by ai-setup. Edit paths if your submodule location differs.
#
# HOW TO USE (Cline / Cursor):
#   There are no slash commands. To invoke an agent, tell the AI:
#   "Follow the workflow in: <path below>"
#   or paste the path into your system prompt / context.

## Lifecycle Agents (invoke in order)

- Stage 1   — Domain research:        .claude/skills/ai-lifecycle/ai-agent-domain-expert/SKILL.md  (capability: domain-research)
- Stage 1.5 — Ideation / PRD:         .claude/skills/ai-lifecycle/ai-agent-domain-expert/SKILL.md  (capability: ideation)
- Stage 2   — EDA:                    .claude/skills/ai-lifecycle/ai-agent-data-engineer/SKILL.md   (capability: eda)
- Stage 3   — Architecture:           .claude/skills/ai-lifecycle/ai-agent-researcher/SKILL.md      (capability: architecture)
- Stage 4   — Detailed Design:        .claude/skills/ai-lifecycle/ai-agent-researcher/SKILL.md      (capability: detailed-design)
- Stage 4.5 — TECHSPEC:               .claude/skills/ai-lifecycle/ai-agent-mlops-engineer/SKILL.md       (capability: techspec)
- Stage 5   — Infrastructure:         .claude/skills/ai-lifecycle/ai-agent-mlops-engineer/SKILL.md       (capability: infra)
- Stage 6   — Experiment:             .claude/skills/ai-lifecycle/ai-agent-experimentation-engineer/SKILL.md        (capability: experiment)
- Stage 6.5 — Results:                .claude/skills/ai-lifecycle/ai-agent-experimentation-engineer/SKILL.md        (capability: results)
- Stage 7   — Analysis:               .claude/skills/ai-lifecycle/ai-agent-researcher/SKILL.md      (capability: analysis)
- Stage 7.5 — HPO (conditional):      .claude/skills/ai-lifecycle/ai-agent-experimentation-engineer/SKILL.md        (capability: hparam)
- Stage 8   — Revision:               .claude/skills/ai-lifecycle/ai-agent-domain-expert/SKILL.md   (capability: revision-audit)

## Universal Tools (invoke anytime)

- Advise (surface past findings):     .claude/skills/ai-lifecycle/ai-agent-domain-expert/SKILL.md   (capability: advise)
- Inference pipeline:                 .claude/skills/ai-lifecycle/ai-agent-mlops-engineer/SKILL.md        (capability: inference-pipeline)

## Experiment Tracking

Chosen tool: {tracking_tool}
Configure in ai-agent-mlops-engineer infra (Stage 5).

## LLM Engine

The model is set in your IDE settings — not here.
For scripts calling an LLM programmatically: configs/llm_config.yaml + scripts/llm_client.py

## Key Principles

- No packages installed until ai-agent-mlops-engineer infra (Stage 5) runs `uv sync`.
- Package requirements are written to pyproject.toml in ai-agent-domain-expert ideation (Stage 1.5).
- TECHSPECs are contracts — never modify after training starts.
"""

# ---------------------------------------------------------------------------
# CLAUDE.md template (Claude Code)
# ---------------------------------------------------------------------------
CLAUDE_MD_TEMPLATE = """\
# AI Lifecycle — Project Rules
# Auto-generated by ai-setup.

## Available Agents

| Slash Command | Stages | Role |
|---------------|--------|------|
| /ai-agent-domain-expert | 1, 1.5, 8, anytime | Domain Expert — domain research, problem framing, PRD, advise, revision audit |
| /ai-agent-data-engineer | 2 | Data Engineer — EDA, baseline, data quality |
| /ai-agent-researcher | 3, 4, 7 | AI Researcher — architecture, detailed design, analysis |
| /ai-agent-mlops-engineer | 4.5, 5, anytime | ML/MLOps Engineer — TECHSPEC, infrastructure, inference pipeline |
| /ai-agent-experimentation-engineer | 6, 6.5, 7.5 | Experimentation Engineer — experiments, results, HPO |

After invoking an agent, tell it which capability to activate (e.g. "run domain-research", "run architecture").

## Experiment Tracking

Chosen tool: {tracking_tool}
Configure in ai-agent-mlops-engineer infra (Stage 5).

## LLM Engine

The model executing these agents is the one selected in your Claude Code model picker.
No project-level override needed.

For scripts that call an LLM programmatically:
  Config: configs/llm_config.yaml  (provider / model / api_key_env / base_url)
  Usage:  from scripts.llm_client import LLMClient

## Package Management

This project uses **uv**. Do NOT use pip or python -m venv.

- Add packages: `uv add <package>`
- Sync environment: `uv sync`
- Run scripts: `uv run python scripts/...`

Packages are added to pyproject.toml in ai-agent-domain-expert ideation (Stage 1.5).
The first `uv sync` runs in ai-agent-mlops-engineer infra (Stage 5) as part of the smoke test.
"""

# ---------------------------------------------------------------------------
# .gitignore
# ---------------------------------------------------------------------------
GITIGNORE = """\
# Python
__pycache__/
*.py[cod]
*.egg-info/
dist/
build/
.venv/
.uv/

# uv
uv.lock

# Jupyter
.ipynb_checkpoints/
*.ipynb

# AI/ML artifacts
checkpoints/
*.ckpt
*.pt
*.pth
*.onnx
*.tflite
*.pkl
*.joblib

# Experiment tracking
mlruns/
wandb/
logs/
*.log

# Data (keep structure, ignore content)
data/raw/*
data/processed/*
data/splits/*
!data/raw/.gitkeep
!data/processed/.gitkeep
!data/splits/.gitkeep

# Internal-source exports (often contain sensitive data — keep local)
imports/*
!imports/README.md

# Secrets
.env
*.env
secrets.json

# OS
.DS_Store
Thumbs.db
"""

# ---------------------------------------------------------------------------
# imports/README.md — export drop-folder guide
# ---------------------------------------------------------------------------
IMPORTS_README = """\
# imports/ — Internal-Source Export Drop Folder

Exports from internal systems land here when a source has no MCP server
(air-gapped / corporate fallback). The whole folder is **gitignored** except
this README — exports often contain sensitive internal data.

Expected export formats per subfolder:

| Folder | Contents |
|--------|----------|
| `jira/` | CSV or XML exports (Issue Navigator -> Export); one file per JQL query |
| `confluence/` | Space exports (HTML or XML zip, unzipped) or individual page PDFs |
| `sharepoint/` | Downloaded documents (PDF/DOCX/XLSX), preserving library folder structure |
| `docs/` | Loose PDFs, specs, datasheets from network shares |

Optional: add a `MANIFEST.md` describing what each export contains and when
it was pulled. Research agents inventory this folder first and cite file
paths (e.g. `imports/jira/postmortems-2025.csv`) in the Domain Knowledge Base.

Air-gapped note: reference PDFs do not have to live here — agents will also
ask for a background folder at any path you name.
"""

# ---------------------------------------------------------------------------
# pyproject.toml skeleton (uv-compatible, no dependencies)
# ---------------------------------------------------------------------------
PYPROJECT_TEMPLATE = """\
[project]
name = "{project_name}"
version = "0.1.0"
description = "Generated by ai-setup. Add description after ai-agent-domain-expert ideation."
requires-python = ">={python_version}"
dependencies = []
# Dependencies are added in ai-agent-domain-expert ideation (Stage 1.5) and installed
# in ai-agent-mlops-engineer infra (Stage 5) via: uv sync

[project.optional-dependencies]
dev = [
    "pytest>=8.0",
    "pytest-cov>=5.0",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.pytest.ini_options]
testpaths = ["tests"]
"""

# ---------------------------------------------------------------------------
# configs/project_infra.yaml template
# ---------------------------------------------------------------------------
INFRA_CONFIG_TEMPLATE = """\
# Project infrastructure — generated by ai-setup (scaffold time).
# TECHSPEC (Stage 4.5) reads this when writing the compute-placement section;
# infra (Stage 5) reads it to provision data access, artifact storage, and
# training execution. Edit here if infrastructure decisions change.
data:
  location: {data_location}        # local / s3 / gcs / azure-blob / nfs
  uri: {data_uri}
artifacts:
  registry: {artifact_registry}    # tracker-native / s3 / gcs / local
  uri: {artifact_uri}
compute:
  topology: {compute}              # same-machine / remote-gpu / cloud-managed
  service: {compute_service}       # vertex-ai / clearml / generic (cloud-managed only)
"""

# ---------------------------------------------------------------------------
# docker/Dockerfile.train template
# ---------------------------------------------------------------------------
DOCKERFILE_TRAIN_TEMPLATE = """\
# syntax=docker/dockerfile:1
# ---------------------------------------------------------------------------
# Dockerfile.train — multi-purpose training image (generated by ai-setup).
#
# Built at Stage 5+ (ai-agent-mlops-engineer infra), NOT at scaffold time.
# Prerequisite: run `uv lock` first — `uv sync --frozen` below needs uv.lock.
#
# GPU note: for CUDA training swap the base image for a CUDA variant, e.g.
#   FROM nvidia/cuda:12.4.1-cudnn-runtime-ubuntu22.04
# then install Python {python_version} inside it (e.g. `uv python install {python_version}`)
# and keep the rest of this file unchanged.
# ---------------------------------------------------------------------------
FROM python:{python_version}-slim

# uv is the only package manager in this project (no pip)
COPY --from=ghcr.io/astral-sh/uv:latest /uv /uvx /bin/

ENV UV_LINK_MODE=copy \\
    UV_COMPILE_BYTECODE=1 \\
    PYTHONUNBUFFERED=1

WORKDIR /app

# --- Dependency layer: cached until pyproject.toml / uv.lock change ---------
COPY pyproject.toml uv.lock ./
RUN uv sync --frozen --no-install-project --no-dev

# --- Project code: separate layer so code edits don't bust the dep cache ----
COPY src/ src/
COPY configs/ configs/
COPY scripts/ scripts/
RUN uv sync --frozen --no-dev

ENV PATH="/app/.venv/bin:$PATH"

# ---------------------------------------------------------------------------
# Entrypoint placeholder — point this at the training script once the
# TECHSPEC (Stage 4.5) fixes the experiment entry point, e.g.:
#   ENTRYPOINT ["python", "-m", "src.<project_name>.train"]
# ---------------------------------------------------------------------------
ENTRYPOINT ["python", "--version"]
"""

# ---------------------------------------------------------------------------
# docker/README.md template — {vertex_mark}/{clearml_mark}/{generic_mark} tag
# the section matching the chosen compute service.
# ---------------------------------------------------------------------------
DOCKER_README_TEMPLATE = """\
# Dockerized Training

Generated by ai-setup. Configured compute: **{compute}**{service_note}.
The image is built at Stage 5+ (infra) — never at scaffold time.

## Build

```bash
uv lock                      # Dockerfile.train uses `uv sync --frozen`
docker build -f docker/Dockerfile.train -t {project_name}-train:latest .
```

Set the `ENTRYPOINT` in `Dockerfile.train` to your training script first
(fixed by the TECHSPEC in Stage 4.5).

## Vertex AI custom jobs{vertex_mark}

Push to Artifact Registry, then submit a custom job:

```bash
docker tag {project_name}-train:latest REGION-docker.pkg.dev/PROJECT/REPO/{project_name}-train:latest
docker push REGION-docker.pkg.dev/PROJECT/REPO/{project_name}-train:latest
gcloud ai custom-jobs create --region=REGION \\
  --display-name={project_name}-train \\
  --worker-pool-spec=machine-type=n1-standard-8,accelerator-type=NVIDIA_TESLA_T4,accelerator-count=1,replica-count=1,container-image-uri=REGION-docker.pkg.dev/PROJECT/REPO/{project_name}-train:latest
```

## ClearML Agent queues{clearml_mark}

Run a ClearML Agent in docker mode against a queue; tasks reference this image:

```bash
clearml-agent daemon --queue gpu --docker {project_name}-train:latest
# enqueue from code: task.execute_remotely(queue_name="gpu")
```

The agent injects the ClearML SDK at runtime; keep the image tracker-agnostic.

## Generic docker run / Kubernetes{generic_mark}

```bash
docker run --rm --gpus all \\
  -v $(pwd)/data:/app/data -v $(pwd)/configs:/app/configs \\
  {project_name}-train:latest
```

For Kubernetes, wrap the same image in a `Job` manifest (set `resources.limits`
with `nvidia.com/gpu: 1` for GPU nodes) and mount data via PVC or object-store CSI.
"""


def create_dirs(root: Path, project_name: str) -> None:
    dirs = [
        "docs/prd",
        "docs/eda",
        "docs/architecture",
        "docs/design",
        "docs/techspecs",
        "docs/implementation",
        "docs/experiments",
        "docs/revisions",
        "docs/knowledge",
        "data/raw",
        "data/processed",
        "data/splits",
        f"src/{project_name}",
        "tests",
        "scripts",
        "logs",
        "notebooks",
        "configs",
    ]
    for d in dirs:
        (root / d).mkdir(parents=True, exist_ok=True)

    # Placeholder files so git tracks empty dirs
    for d in ["data/raw", "data/processed", "data/splits", "logs"]:
        keep = root / d / ".gitkeep"
        if not keep.exists():
            keep.touch()

    # Minimal __init__.py files
    for init_dir in [f"src/{project_name}", "tests"]:
        init_file = root / init_dir / "__init__.py"
        if not init_file.exists():
            init_file.write_text("", encoding='utf-8')


def write_imports_tree(root: Path) -> None:
    """Create the imports/ export drop-folder tree (gitignored except README.md)."""
    imports_dir = root / "imports"
    for sub in ["jira", "confluence", "sharepoint", "docs"]:
        (imports_dir / sub).mkdir(parents=True, exist_ok=True)

    readme = imports_dir / "README.md"
    if not readme.exists():
        readme.write_text(IMPORTS_README, encoding='utf-8')
        print(f"  Wrote: imports/README.md (export drop-folder guide; imports/ is gitignored)")
    else:
        print(f"  Skipped: imports/README.md (already exists)")


def write_clinerules(root: Path, ide: str, tracking_tool: str) -> None:
    content = CLINERULES_TEMPLATE.format(tracking_tool=tracking_tool)
    if ide == "claude-code":
        out = root / ".claude" / "CLAUDE.md"
        out.parent.mkdir(exist_ok=True)
        out.write_text(CLAUDE_MD_TEMPLATE.format(tracking_tool=tracking_tool), encoding='utf-8')
        print(f"  Wrote: .claude/CLAUDE.md")
    else:
        out = root / ".clinerules"
        out.write_text(content, encoding='utf-8')
        print(f"  Wrote: .clinerules")


def write_gitignore(root: Path) -> None:
    gi = root / ".gitignore"
    if not gi.exists():
        gi.write_text(GITIGNORE, encoding='utf-8')
        print(f"  Wrote: .gitignore")
    else:
        print(f"  Skipped: .gitignore (already exists)")


def write_pyproject(root: Path, project_name: str, python_version: str) -> None:
    pf = root / "pyproject.toml"
    if not pf.exists():
        pf.write_text(PYPROJECT_TEMPLATE.format(
            project_name=project_name,
            python_version=python_version,
        ), encoding='utf-8')
        print(f"  Wrote: pyproject.toml (no dependencies — added in Stage 1.5)")
    else:
        print(f"  Skipped: pyproject.toml (already exists)")


def write_python_version(root: Path, python_version: str) -> None:
    pv = root / ".python-version"
    if not pv.exists():
        pv.write_text(python_version + "\n", encoding='utf-8')
        print(f"  Wrote: .python-version ({python_version})")


def run_uv_init(root: Path, project_name: str) -> None:
    """Run `uv init` to initialise the project, then clean up uv's boilerplate."""
    pf = root / "pyproject.toml"
    existed_before = pf.exists()

    result = subprocess.run(
        ["uv", "init", "--name", project_name, "--no-readme", "--no-workspace"],
        cwd=root,
        capture_output=True,
        text=True,
    )
    if result.returncode != 0:
        if not existed_before:
            print(f"  Warning: `uv init` failed ({result.stderr.strip()}). Will write pyproject.toml manually.")
        else:
            print(f"  Skipped: uv init (pyproject.toml already exists)")
        return

    print(f"  Ran: uv init")

    # uv init creates main.py — remove it, we use src layout
    main_py = root / "main.py"
    if main_py.exists():
        main_py.unlink()
        print(f"  Removed: main.py (using src/ layout instead)")

    # Overwrite uv's minimal pyproject.toml with our richer template
    if not existed_before:
        pf.unlink(missing_ok=True)


def run_uv_venv(root: Path) -> None:
    """Create an EMPTY virtual environment via `uv venv` (no packages installed)."""
    if (root / ".venv").exists():
        print(f"  Skipped: uv venv (.venv already exists)")
        return
    try:
        result = subprocess.run(
            ["uv", "venv"], cwd=root, capture_output=True, text=True,
        )
    except FileNotFoundError:
        print(f"  Warning: uv not found — create the venv later with `uv venv`.")
        return
    if result.returncode != 0:
        print(f"  Warning: `uv venv` failed ({result.stderr.strip()}). Create it later with `uv venv`.")
    else:
        print(f"  Ran: uv venv (.venv created — empty, no packages until Stage 5)")


def run_git_init(root: Path) -> bool:
    """Initialise a git repository on branch `main`. Returns True if a repo exists after."""
    if (root / ".git").exists():
        print(f"  Skipped: git init (.git already exists)")
        return True
    try:
        result = subprocess.run(
            ["git", "init", "-b", "main"], cwd=root, capture_output=True, text=True,
        )
        if result.returncode != 0:
            # Older git without `-b` support
            result = subprocess.run(
                ["git", "init"], cwd=root, capture_output=True, text=True,
            )
    except FileNotFoundError:
        print(f"  Warning: git not found — initialise the repo later with `git init -b main`.")
        return False
    if result.returncode != 0:
        print(f"  Warning: `git init` failed ({result.stderr.strip()}).")
        return False
    print(f"  Ran: git init -b main")
    return True


def run_git_commit_and_remote(root: Path, git_remote: str | None) -> None:
    """Commit the scaffold and register the remote. NEVER pushes automatically."""
    if not (root / ".git").exists():
        return
    try:
        subprocess.run(["git", "add", "-A"], cwd=root, capture_output=True, text=True)
        result = subprocess.run(
            ["git", "commit", "-m", "chore: scaffold AI/ML project structure"],
            cwd=root, capture_output=True, text=True,
        )
    except FileNotFoundError:
        return
    if result.returncode != 0:
        print(f"  Warning: git commit failed ({(result.stderr or result.stdout).strip()}). Commit manually.")
    else:
        print(f"  Committed: scaffold on branch main")

    if git_remote:
        has_origin = subprocess.run(
            ["git", "remote", "get-url", "origin"], cwd=root, capture_output=True, text=True,
        )
        if has_origin.returncode == 0:
            print(f"  Skipped: remote add (origin already exists)")
        else:
            result = subprocess.run(
                ["git", "remote", "add", "origin", git_remote],
                cwd=root, capture_output=True, text=True,
            )
            if result.returncode == 0:
                print(f"  Added remote: origin -> {git_remote} (not pushed — see next steps)")
            else:
                print(f"  Warning: could not add remote ({result.stderr.strip()})")


def write_infra_config(
    root: Path,
    data_location: str,
    data_uri: str | None,
    artifact_registry: str,
    artifact_uri: str | None,
    compute: str,
    compute_service: str | None,
) -> None:
    """Write configs/project_infra.yaml — read by TECHSPEC (4.5) and infra (5)."""
    dest = root / "configs" / "project_infra.yaml"
    if dest.exists():
        print(f"  Skipped: configs/project_infra.yaml (already exists)")
        return
    dest.write_text(INFRA_CONFIG_TEMPLATE.format(
        data_location=data_location,
        data_uri=data_uri or "~",
        artifact_registry=artifact_registry,
        artifact_uri=artifact_uri or "~",
        compute=compute,
        compute_service=compute_service or "~",
    ), encoding='utf-8')
    print(f"  Wrote: configs/project_infra.yaml (data/artifacts/compute decisions)")


def write_docker_templates(
    root: Path,
    project_name: str,
    python_version: str,
    compute: str,
    compute_service: str | None,
) -> None:
    """Write docker/Dockerfile.train + docker/README.md training templates."""
    docker_dir = root / "docker"
    docker_dir.mkdir(exist_ok=True)

    dockerfile = docker_dir / "Dockerfile.train"
    if not dockerfile.exists():
        dockerfile.write_text(
            DOCKERFILE_TRAIN_TEMPLATE.format(python_version=python_version),
            encoding='utf-8',
        )
        print(f"  Wrote: docker/Dockerfile.train (built at Stage 5+, not now)")
    else:
        print(f"  Skipped: docker/Dockerfile.train (already exists)")

    readme = docker_dir / "README.md"
    if not readme.exists():
        mark = "  <- configured target"
        readme.write_text(DOCKER_README_TEMPLATE.format(
            project_name=project_name.replace("_", "-"),
            compute=compute,
            service_note=f" via **{compute_service}**" if compute_service else "",
            vertex_mark=mark if compute_service == "vertex-ai" else "",
            clearml_mark=mark if compute_service == "clearml" else "",
            generic_mark=mark if compute_service in (None, "generic") else "",
        ), encoding='utf-8')
        print(f"  Wrote: docker/README.md (build + job submission patterns)")
    else:
        print(f"  Skipped: docker/README.md (already exists)")


def write_llm_config(root: Path, skill_dir: Path) -> None:
    """
    Copy llm_config.yaml.template to configs/llm_config.yaml in the project.

    This config is ONLY for scripts that call an LLM programmatically via
    llm_client.py. The model running the agent prompts is set inside
    the IDE (Cline / Antigravity / Claude Code) — not here.
    """
    dest = root / "configs" / "llm_config.yaml"
    if dest.exists():
        print(f"  Skipped: configs/llm_config.yaml (already exists)")
        return

    template = skill_dir / "llm_config.yaml.template"
    if template.exists():
        shutil.copy2(template, dest)
        print(f"  Wrote: configs/llm_config.yaml (edit to configure programmatic LLM calls)")
    else:
        dest.write_text(
            "# AI Lifecycle LLM config — for scripts/llm_client.py only.\n"
            "# The agent model is set in your IDE settings.\n"
            "# provider: anthropic | openai-compatible (OpenAI, Ollama, vLLM, Azure, ...)\n"
            "provider: anthropic\n"
            "model: <your-model-name>  # e.g. claude-sonnet-4-6, gpt-4o, llama3.3\n"
            "base_url: ~               # null → provider's default endpoint\n"
            "api_key_env: ANTHROPIC_API_KEY  # or OPENAI_API_KEY etc., matching your provider\n"
            "max_tokens: 8192\n"
            "temperature: 0.0\n",
            encoding='utf-8',
        )
        print(f"  Wrote: configs/llm_config.yaml (minimal fallback — template not found)")


def register_in_bmad_help(root: Path, skill_dir: Path) -> None:
    """
    Register all ai-lifecycle skills in _bmad/_config/bmad-help.csv.
    """
    csv_path = root / "_bmad" / "_config" / "bmad-help.csv"
    if not csv_path.exists():
        print(f"  Skipped: {csv_path} not found (not a BMAD project root?)")
        return

    our_csv = skill_dir.parent / "ai-lifecycle.csv"
    if not our_csv.exists():
        print(f"  Skipped: ai-lifecycle.csv not found in module root")
        return

    existing = csv_path.read_text(encoding="utf-8")
    our_rows = our_csv.read_text(encoding="utf-8").strip()

    # Remove any existing ai rows, then append current ones
    kept = [line for line in existing.splitlines() if not line.startswith("ai,")]
    updated = "\n".join(kept).rstrip() + "\n" + our_rows + "\n"
    csv_path.write_text(updated, encoding="utf-8")
    print(f"  Updated: _bmad/_config/bmad-help.csv (ai-lifecycle rows replaced)")


def copy_claude_skills(root: Path, skill_dir: Path) -> None:
    """
    Copy all ai-lifecycle SKILL.md + bmad-manifest.json files into .claude/skills/
    so that Claude Code can discover them as slash commands.
    """
    module_root = skill_dir.parent  # scripts/ -> ai-lifecycle/ (module root)
    dest_root = root / ".claude" / "skills"
    dest_root.mkdir(parents=True, exist_ok=True)

    copied = []
    for agent_dir in module_root.glob("ai-agent-*/"):
        skill_md = agent_dir / "SKILL.md"
        manifest = agent_dir / "bmad-manifest.json"
        if not skill_md.exists():
            continue
        dest_skill = dest_root / agent_dir.name
        dest_skill.mkdir(exist_ok=True)
        shutil.copy2(skill_md, dest_skill / "SKILL.md")
        if manifest.exists():
            shutil.copy2(manifest, dest_skill / "bmad-manifest.json")
        copied.append(agent_dir.name)

    if copied:
        print(f"  Copied {len(copied)} agents → .claude/skills/ (slash commands now available)")
    else:
        print(f"  Warning: no agent skill files found to copy into .claude/skills/")


def copy_scripts(root: Path, skill_dir: Path) -> None:
    """Copy ai-lifecycle utility scripts (including llm_client.py) into project scripts/."""
    scripts_dir = root / "scripts"
    module_root = skill_dir.parent

    copied = []

    # Copy llm_client.py from our own scripts dir
    llm_client_src = skill_dir / "llm_client.py"
    if llm_client_src.exists():
        dest = scripts_dir / "llm_client.py"
        if not dest.exists():
            shutil.copy2(llm_client_src, dest)
            copied.append("llm_client.py")

    # Copy all other utility scripts from agent script directories
    for agent_scripts in module_root.glob("ai-agent-*/scripts/*.py"):
        if agent_scripts.name.startswith("test_") or agent_scripts.name == "llm_client.py":
            continue
        dest = scripts_dir / agent_scripts.name
        if not dest.exists():
            shutil.copy2(agent_scripts, dest)
            copied.append(agent_scripts.name)

    if copied:
        print(f"  Copied {len(copied)} utility scripts → scripts/")
    else:
        print(f"  No utility scripts found to copy (run from skill directory)")


def _ask(prompt: str, default: str, choices: list[str] | None = None) -> str:
    """Prompt the user for input, showing the default and optional choices.

    When stdin is exhausted (e.g. answers were piped in for only the first
    questions), fall back to the default instead of aborting — this keeps
    old `printf "..." | uv run init_project.py` invocations working.
    """
    if choices:
        options = "/".join(
            f"[{c}]" if c == default else c for c in choices
        )
        display = f"{prompt} ({options}): "
    else:
        display = f"{prompt} [{default}]: "
    try:
        answer = input(display).strip()
    except EOFError:
        print(f"(stdin exhausted — using default: {default or 'none'})")
        return default
    except KeyboardInterrupt:
        print()
        sys.exit(0)
    return answer if answer else default


def _resolve(
    flag_value: str | None,
    assume_yes: bool,
    prompt: str,
    default: str,
    choices: list[str] | None = None,
) -> str:
    """Answer from CLI flag if given, default if --yes, else interactive prompt."""
    if flag_value is not None:
        return flag_value
    if assume_yes:
        return default
    return _ask(prompt, default, choices)


def parse_args(argv: list[str] | None = None) -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Scaffold an AI/ML project (ai-setup). "
                    "Any flag not given is asked interactively (or defaulted with --yes).",
    )
    parser.add_argument("--ide", choices=["claude-code", "cline", "cursor", "antigravity"],
                        help="Target IDE (default: cline)")
    parser.add_argument("--tracker", choices=["wandb", "mlflow", "clearml", "undecided"],
                        help="Experiment tracking tool (default: undecided)")
    parser.add_argument("--python-version", help="Python version (default: 3.11)")
    parser.add_argument("--data-location", choices=["local", "s3", "gcs", "azure-blob", "nfs"],
                        help="Where training data lives (default: local)")
    parser.add_argument("--data-uri", help="Optional data URI/path (e.g. s3://bucket/prefix)")
    parser.add_argument("--artifact-registry", choices=["tracker-native", "s3", "gcs", "local"],
                        help="Where model artifacts go (default: tracker-native if a tracker "
                             "was chosen, else local)")
    parser.add_argument("--artifact-uri", help="Optional artifact store URI")
    parser.add_argument("--compute", choices=["same-machine", "remote-gpu", "cloud-managed"],
                        help="Training compute topology (default: same-machine)")
    parser.add_argument("--compute-service", choices=["vertex-ai", "clearml", "generic"],
                        help="Managed service when --compute cloud-managed (default: generic)")
    parser.add_argument("--git-remote", help="Git remote URL for origin, or 'none' (default: none). "
                                             "Never pushed automatically.")
    parser.add_argument("--yes", "-y", action="store_true",
                        help="Non-interactive: use defaults for anything not given as a flag")
    return parser.parse_args(argv)


def main(argv: list[str] | None = None) -> None:
    args = parse_args(argv)
    root = Path.cwd()
    project_name = root.name.replace("-", "_").replace(" ", "_")

    print(f"\nai-setup: Scaffolding '{project_name}' in {root}\n")

    yes = args.yes
    # Question order preserved so the legacy printf pipe still maps correctly:
    # ide, tracker, python_version, copy_scripts — then the new infra questions.
    ide = _resolve(
        args.ide, yes, "IDE", "cline",
        choices=["claude-code", "cline", "cursor", "antigravity"],
    )
    tracking_tool = _resolve(
        args.tracker, yes,
        "Experiment tracking tool (can be changed in Architecture stage)",
        "undecided",
        choices=["wandb", "mlflow", "clearml", "undecided"],
    )
    python_version = _resolve(args.python_version, yes, "Python version", "3.11")
    copy_scripts_flag = _resolve(None, yes, "Copy ai-lifecycle utility scripts?", "yes",
                                 choices=["yes", "no"])

    # Infra questions (new) — flags first, safe defaults on --yes or exhausted stdin
    data_location = _resolve(
        args.data_location, yes, "Data location", "local",
        choices=["local", "s3", "gcs", "azure-blob", "nfs"],
    )
    data_uri = _resolve(args.data_uri, yes, "Data URI/path (optional, empty to skip)", "")
    default_registry = "tracker-native" if tracking_tool != "undecided" else "local"
    artifact_registry = _resolve(
        args.artifact_registry, yes, "Artifact registry", default_registry,
        choices=["tracker-native", "s3", "gcs", "local"],
    )
    artifact_uri = _resolve(args.artifact_uri, yes, "Artifact URI (optional, empty to skip)", "")
    compute = _resolve(
        args.compute, yes, "Compute topology", "same-machine",
        choices=["same-machine", "remote-gpu", "cloud-managed"],
    )
    compute_service = None
    if compute == "cloud-managed":
        compute_service = _resolve(
            args.compute_service, yes, "Managed compute service", "generic",
            choices=["vertex-ai", "clearml", "generic"],
        )
    git_remote = _resolve(args.git_remote, yes, "Git remote URL (or 'none')", "none")
    if git_remote.lower() in ("", "none"):
        git_remote = None

    print()

    print("Initialising git repository...")
    git_ok = run_git_init(root)

    print("Creating directory structure...")
    create_dirs(root, project_name)
    write_imports_tree(root)

    print("Writing config files...")
    write_clinerules(root, ide, tracking_tool)
    write_gitignore(root)
    write_python_version(root, python_version)

    print("Writing infrastructure config...")
    write_infra_config(root, data_location, data_uri, artifact_registry,
                       artifact_uri, compute, compute_service)

    print("Writing docker training templates...")
    write_docker_templates(root, project_name, python_version, compute, compute_service)

    print("Initialising uv project...")
    run_uv_init(root, project_name)
    write_pyproject(root, project_name, python_version)

    print("Creating virtual environment (empty — no packages installed)...")
    run_uv_venv(root)

    print("Writing LLM config...")
    script_dir = Path(__file__).parent
    write_llm_config(root, script_dir)

    print("Registering skills in bmad-help.csv...")
    register_in_bmad_help(root, script_dir)

    if ide == "claude-code":
        print("Copying agents to .claude/skills/ (enables slash commands)...")
        copy_claude_skills(root, script_dir)

    if copy_scripts_flag != "no":
        print("Copying ai-lifecycle utility scripts...")
        copy_scripts(root, script_dir)

    print("Committing scaffold...")
    run_git_commit_and_remote(root, git_remote)

    if ide in ("cline", "cursor"):
        stage1_instruction = (
            '  Open your IDE and tell the AI:\n'
            '  "Follow the workflow in: .claude/skills/ai-lifecycle/ai-agent-domain-expert/SKILL.md"\n'
            '  Tell it to activate the domain-research capability.\n'
            '  (All agent paths are listed in .clinerules for quick reference)'
        )
    else:
        stage1_instruction = "  Use slash command: /ai-agent-domain-expert  (then: activate domain-research)"

    if git_remote:
        remote_line = f"origin -> {git_remote} (NOT pushed — run: git push -u origin main)"
    else:
        remote_line = "none configured (add later: git remote add origin <url>)"

    print(f"""
Project scaffolded at: {root}

Environment:
  - venv:   .venv created via `uv venv` (empty — first install is Stage 5's `uv sync`)
  - git:    {"initialised on 'main', scaffold committed" if git_ok else "NOT initialised (git unavailable)"}
  - remote: {remote_line}
  - infra:  configs/project_infra.yaml (data: {data_location}, artifacts: {artifact_registry}, compute: {compute}{f" via {compute_service}" if compute_service else ""})
  - docker: docker/Dockerfile.train + docker/README.md (image built at Stage 5+, not now)

Next steps:
  1. Activate the venv: source .venv/bin/activate  (or just use uv run)
  2. {"Push when ready: git push -u origin main" if git_remote else "Optionally add a git remote: git remote add origin <url>"}
  3. Start Stage 1 — Domain Expert researches the problem space:
{stage1_instruction}
     The agent determines required packages and writes them to pyproject.toml.
  4. Stage 5 (ai-agent-mlops-engineer infra) runs: uv sync  <- FIRST package installation.

Do NOT run `uv sync` or `uv add` before Stage 5.
""")


if __name__ == "__main__":
    main()
